# Generated by Django 5.0.4 on 2024-04-27 11:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('Paragraph_id', models.AutoField(primary_key=True, serialize=False)),
                ('Paragraph_text', models.TextField()),
                ('Paragraph_created_at', models.DateTimeField(auto_now_add=True)),
                ('Paragraph_modified_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('Paragraph_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('CustomUser_dob', models.DateField(blank=True, null=True)),
                ('CustomUser_created_at', models.DateTimeField(auto_now_add=True)),
                ('CustomUser_modified_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions from all of the groups they are promiscuous in.', related_name='custom_users', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='The permissions granted to this user.', related_name='custom_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('Word_id', models.AutoField(primary_key=True, serialize=False)),
                ('Word_text', models.CharField(max_length=355)),
                ('Word_created_at', models.DateTimeField(auto_now_add=True)),
                ('Word_modified_at', models.DateTimeField(auto_now=True)),
                ('Word_paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='ParagraphWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pw_word', models.CharField(max_length=355)),
                ('pw_paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paragraph')),
            ],
            options={
                'unique_together': {('pw_paragraph', 'pw_word')},
            },
        ),
    ]
