"""
URL configuration for project_BD2 project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
# Import necessary modules from Django and REST framework
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from app.views import CustomUserViewSet, ParagraphViewSet, WordViewSet
from app.views import LoginView, ParagraphView, SearchView

# Create a DefaultRouter instance to handle URL routing for REST API
router = DefaultRouter()

# Register view sets with the router
# This will create URLs for CRUD operations on users, paragraphs, and words
router.register(r'users', CustomUserViewSet)
router.register(r'paragraphs', ParagraphViewSet)
router.register(r'words', WordViewSet)

# Define URL patterns for the application
urlpatterns = [
    # URL for admin interface
    path('admin/', admin.site.urls),
    
    # URL for login view
    path('login/', LoginView.as_view()),
    
    # URL for paragraph view
    path('paragraphs/', ParagraphView.as_view()),
    
    # URL for search view
    path('search/', SearchView.as_view()),
    
    # Include URLs generated by the router
    # This will include URLs for users, paragraphs, and words
    path('', include(router.urls)),
    
    # Duplicate inclusion of router URLs (may be unnecessary)
    path('employees/', include(router.urls)),
    
    # Duplicate inclusion of router URLs (may be unnecessary)
    path('api/', include(router.urls)),
]
